# Generated by Django 4.1.7 on 2023-03-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=25)),
                ('account_type', models.CharField(max_length=30)),
                ('materials_providing', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=8)),
                ('c_password', models.CharField(max_length=8)),
            ],
        ),
    ]
