# Generated by Django 4.1.7 on 2023-03-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbank', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_registration',
        ),
    ]
